### PR TITLE
update to pico-sdk-1.4.0

### PR DESCRIPTION
**Pull request by NomiChirps**

### CODE REVIEW

**Comment by NomiChirps** [comment]
Hold on - forgot to update the gen_version rule.

**Comment by dfr** [comment]
This is great! Could you add the new boards for this release to pico/config/BUILD as well.

Longer term, I wanted to add wifi support for pico-w but I don't own the hardware :).

**Comment by dfr** [comment]
Just to clarify - I'm not asking you to add wifi support in this PR, just update the boards list

**Comment by NomiChirps** [comment]
Yep :) Just haven't gotten to it yet.

**Comment by NomiChirps** [comment]
Ok, how does this look? I'd assumed there was more to it, haha.

**Comment by dfr** [comment]
Looks great, thanks!

**Pull request merged**
